// ============================================================================
// CÓDIGOS DE ERRO PADRONIZADOS
// ============================================================================

export enum ErrorCode {
  // Geral
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',

  // Autenticação
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  TENANT_INACTIVE = 'TENANT_INACTIVE',
  TENANT_LIMIT_EXCEEDED = 'TENANT_LIMIT_EXCEEDED',

  // Usuário
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INACTIVE = 'USER_INACTIVE',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Financeiro
  TITLE_NOT_FOUND = 'TITLE_NOT_FOUND',
  TITLE_ALREADY_PAID = 'TITLE_ALREADY_PAID',
  INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT',
  PAYMENT_EXCEEDS_BALANCE = 'PAYMENT_EXCEEDS_BALANCE',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // Estoque
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND',
  TRANSFER_NOT_FOUND = 'TRANSFER_NOT_FOUND',
  INVALID_STOCK_MOVEMENT = 'INVALID_STOCK_MOVEMENT',

  // Vendas
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  PRICE_LIST_NOT_FOUND = 'PRICE_LIST_NOT_FOUND',

  // NFe
  NFE_PARSE_ERROR = 'NFE_PARSE_ERROR',
  NFE_ALREADY_IMPORTED = 'NFE_ALREADY_IMPORTED',
  NFE_NOT_FOUND = 'NFE_NOT_FOUND',
  SUPPLIER_NOT_FOUND = 'SUPPLIER_NOT_FOUND',

  // Asaas
  ASAAS_API_ERROR = 'ASAAS_API_ERROR',
  ASAAS_ACCOUNT_NOT_CONFIGURED = 'ASAAS_ACCOUNT_NOT_CONFIGURED',
  ASAAS_INSUFFICIENT_BALANCE = 'ASAAS_INSUFFICIENT_BALANCE',

  // Database
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
